# https://pages.github.com/versions/
# https://docs.travis-ci.com/user/languages/ruby
# https://github.com/jekyll/jekyll

language: ruby
rvm:
  - &ruby3 2.1.8

git:
  depth: 3

bundler_args: --without benchmark:site:development
cache: bundler
sudo: false

before_script:
  # Was: - bundle update
  - gem install github-pages

script:
  - jekyll --version
  # Was: - bundle exec jekyll build
  - jekyll build
  - ruby _bin/validate-json-index.rb
  # http://localhost:4000

# Currently fails!
after_script: npm test

notifications:
  webhooks:
    - http://accessifywiki-2.appspot.com/travis-hook?debug=1&from=travis
    # - http://iet-embed-acct.open.ac.uk/dev/travis-hook/

# End.
