# https://pages.github.com/versions/
# https://docs.travis-ci.com/user/languages/ruby
# https://github.com/jekyll/jekyll

language: ruby
rvm:
  - &ruby3 2.1.8

bundler_args: --without benchmark:site:development
cache: bundler
sudo: false

before_script:
  # Was: - bundle update
  - gem install github-pages

script:
  # Was: - bundle exec jekyll build
  - jekyll build
  - ruby _bin/validate-json-index.rb
  # http://localhost:4000


#End.
