# https://pages.github.com/versions/
# https://docs.travis-ci.com/user/languages/ruby
# https://github.com/jekyll/jekyll

language: ruby

rvm: &ruby2 2.5.3 # Was: &ruby3 2.1.8

git:
  depth: 3

bundler_args: --without benchmark:site:development
cache: bundler
sudo: false

before_install:
  - gem update --system
  - gem install bundler # upgrade to Bundler 2.0

before_script:
  # Was: - bundle update
  # Was: - gem install github-pages

script:
  - node -v
  - npm -v
  - bundle exec jekyll --version
  - bundle exec jekyll build
  # - ruby _bin/validate-json-index.rb
  # http://localhost:4000

# Currently fails!
after_script: npm test

notifications:
  webhooks:
    - http://accessifywiki-2.appspot.com/travis-hook?debug=1&from=travis
    # - http://iet-embed-acct.open.ac.uk/dev/travis-hook/

# End.
