theme: minima
lang: en-GB

# Site settings
title: Accessify Wiki<i> beta</i>
email: nfreear@yahoo.co.uk
x-subtitle: Fixing the Web for all, one site at a time
description: > # this means to ignore newlines until "baseurl:"
  Fixing the Web for all, one site at a time.
  We are the open, transparent accessibility middleware.

  License for fixes: <a href="https://nfreear.mit-license.org">MIT</a>.

  Other code: <a href="https://gnu.org/licenses/gpl.html">GPL-3.0+</a>.

  Documentation: <a href="https://creativecommons.org/licenses/by/4.0">Creative Commons Attribution</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://accessifywiki.github.io"
x-was-url: "http://accessifywiki.org"  # the base hostname & protocol for your site
twitter_username: AccessifyWiki
github_username:  AccessifyWiki  # Was: nfreear

x-legacy-url: http://accessify.wikia.com/wiki/Accessify_Wiki
x-github-url: https://github.com/accessifywiki/accessifywiki.github.io
x-author-url: https://twitter.com/nfreear

ex:
  # Was: search-index: /search-index.json
  fix_index: /fix/index.json
  fix_index_jsonp: /fix/index.js
  fix_selector: "#fix-api-json"
  fix_regex:
    - <script.+json['"]>(.+?)</script>
    - ms

js_config:
  # Google Analytics.
  analytics_id: UA-40194374-5
  debug: ok

x-custom-nav:
  - <a href="http://accessify.wikia.com/wiki/Accessify_Wiki" title="Accessify wiki on Wikia">Legacy wiki</a>
  #- <a href="#">Test 2</a>

#x-site-message: Hello world! Just a <a href="#">test</a>!

# https://access.ecs.soton.ac.uk/ToolBar/
# https://atbar.org/
#x-atbar: true

plugins: # Was: gems:
  - json
  - yaml
  # "multipost" is not a Gem!

collections:
  # 2x layouts? https://github.com/jekyll/jekyll/issues/3041; https://github.com/saclark/jekyll-multipost
  fixes:
    output: true
    ##layout: [ fix, fix-json ]
    permalink: /fix/:path.html
    # Was: permalink: /wiki/fix::path.html
    # Plus JSON? permalink: /wiki/fix/:path.json

# Requires Jekyll 3.
webrick:
  headers:
    # CORS header.
    Access-Control-Allow-Origin: "*"

keep_files:
  - favicon.ico

exclude:
  - Makefile
  - README.md
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock

include:
  - _pages

# Build settings
markdown: kramdown

#End.
